M48
; DRILL file {KiCad 9.0.7} date 2026-08-20T17:34:48+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-20T17:34:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X111.112Y-80.175
X111.112Y-85.025
T2
X114.142Y-79.875
X114.142Y-85.325
M30
